server:
  port: 8088
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      database: tweetapp
  application:
    name: tweet-app
